tourtracker_app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import SubmitField, DateField, StringField, BooleanField
from wtforms.validators import DataRequired


class TourForm(FlaskForm):
    tour_name = StringField('Tour Name:', validators=[DataRequired()])
    start_date = DateField('Start Date:', validators=[DataRequired()])
    end_date = DateField('End Date:', validators=[DataRequired()])
    # auto_refresh = BooleanField('On Tour')
    submit = SubmitField('Create Tour')

tourtracker_app/main/__init__.py
from flask import Blueprint

bp = Blueprint('main', __name__, template_folder='templates')

from tourtracker_app.main import routes # noqa F401

tourtracker_app/main/routes.py
from flask import render_template, make_response, redirect, url_for, flash, request, app
from flask_jwt_extended import jwt_required, get_jwt_identity, current_user
from tourtracker_app import db, jwt as jwt_extended
from tourtracker_app.models.tour_models import Tour, TourActivities
from tourtracker_app.models.strava_api_models import StravaAccessToken, StravaRefreshToken
from tourtracker_app.main import bp
from tourtracker_app.main.forms import TourForm
import polyline
from requests import HTTPError
from datetime import datetime, date
from tourtracker_app.strava_api_auth.strava_api_utilities import get_strava_activities

# TODO: remove auth elements from database tables
# TODO: do we want to use auth server uuid for all user ID or are we happy to transmit email/username over jwt?
# TODO: update tests


@jwt_extended.invalid_token_loader
def invalid_token(reason):
    return redirect(url_for('auth.login'))


@jwt_extended.unauthorized_loader
def unauthorised_loader(reason):
    return redirect(url_for('auth.login'))


@bp.route('/', methods=['GET'])
@bp.route('/index', methods=['GET'])
@jwt_required(optional=True, locations=['query_string'])
def index():
    print('in index route')
    if current_user:
        token = request.args.get('jwt')
        redirect_url = f"{url_for('main.user_profile')}?jwt={token}"
        return redirect(redirect_url)
        #return redirect(url_for('main.user_profile'))
    return render_template('index.html')


@bp.app_template_filter('timestamp_to_str')
def timestamp_to_str(timestamp):
    return date.fromtimestamp(timestamp)

@bp.route('/profile')
@jwt_required(locations=['query_string', 'headers'])
def user_profile():
    form = TourForm()
    print(current_user.username)
    if current_user.strava_athlete_id is not None: # TODO probably a better/more robust way to do this
        strava_authenticated = True
    else:
        strava_authenticated = False

    return render_template('user_profile.html',
                           username=current_user.username,
                           strava_authenticated=strava_authenticated,
                           is_admin=current_user.isadmin,
                           user_tours=current_user.tours,
                           form=form) #TODO put in logic for if we are not linked to strava


@bp.route('/tour/<uuid>', methods=['GET'])
@jwt_required()
def tour_detail(uuid):
    tour = db.session.execute(db.select(Tour).filter_by(tour_uuid=uuid)).first()
    tour = tour[0]
    return render_template('tourdetail.html', tour=tour)

@bp.route('/tour/embed/<uuid>', methods=['GET'])
def tour_embed(uuid):
    tour = db.session.execute(db.select(Tour).filter_by(tour_uuid=uuid)).first()
    tour = tour[0]
    return render_template('tourembed.html', tour=tour)


@bp.route('/tour/data/<uuid>', methods=['GET'])
def get_tour_activities(uuid):
    tour_activities_result = db.session.execute(db.select(TourActivities.strava_activity_id, 
                                                          TourActivities.activity_name,
                                                          TourActivities.activity_date,
                                                          TourActivities.summary_polyline).filter_by(parent_tour=uuid).order_by(TourActivities.activity_date.asc())).all()

    tour_activities = []
    for row in tour_activities_result:
        row_dict = row._asdict()
        points = polyline.decode(row_dict['summary_polyline'])
        latlong = []
        for point in points:
            latlong.append({'lat': point[0], 'lng': point[1]})
        row_dict['points'] = latlong
        row_dict.pop('summary_polyline')
        tour_activities.append(row_dict)
    return make_response(tour_activities, 200)


@bp.route('/createtour', methods=['GET', 'POST'])
@jwt_required()
def create_tour():
    if request.method == 'GET':
        form = TourForm()
        if current_user.strava_athlete_id is not None:  # TODO probably a better/more robust way to do this
            strava_authenticated = True
        else:
            # FIXME is this code even reachable if we don't show create tour button
            # FIXME on user profile template? Guess user could follow direct URL
            strava_authenticated = False
        return render_template('create_tour.html',
                               strava_authenticated=strava_authenticated,
                               form=form)  # TODO put in logic for if we are not linked to strava
    if request.method == 'POST':
        form = TourForm()
        if form.validate_on_submit():
            tour_name = form.tour_name.data

            start_timestamp = (datetime(form.start_date.data.year, form.start_date.data.month, form.start_date.data.day)).timestamp()
            end_timestamp = (datetime(form.end_date.data.year, form.end_date.data.month, form.end_date.data.day)).timestamp()

            # if form.auto_refresh.data is True:
            #     refresh_interval = 21600
            #     last_refresh = int(round(datetime.now().timestamp()))
            # else:
            #     refresh_interval = None
            #     last_refresh = None

            tour = Tour(
                tour_name=tour_name,
                start_date=start_timestamp,
                end_date=end_timestamp,
                # auto_refresh=form.auto_refresh.data,
                user_id=current_user.uuid
            )
            db.session.add(tour)
            db.session.commit()

            activities = get_strava_activities(current_user, start_timestamp, end_timestamp)
            for activity in activities:
                new_activity = TourActivities(
                    strava_activity_id=activity['activity_id'],
                    activity_name=activity['activity_name'],
                    activity_date=activity['activity_date'],
                    summary_polyline=activity['polyline'],
                    parent_tour=tour.tour_uuid,
                    user_id=current_user.uuid
                )
                db.session.add(new_activity)
            db.session.commit()
            return redirect(url_for('main.tour_detail', uuid=tour.tour_uuid))

        flash('Site linking error!')
        print(form.errors)
        return redirect(url_for('main.user_profile'))


@bp.route('/tour/refresh/<uuid>', methods=['GET'])
@jwt_required()
def refresh_tour(uuid):
    tour = db.session.execute(db.select(Tour).filter_by(tour_uuid=uuid)).first()
    activities = get_strava_activities(current_user, tour[0].start_date, tour[0].end_date)
    for activity in activities:
        db.session.merge(TourActivities(
            strava_activity_id=activity['activity_id'],
            activity_name=activity['activity_name'],
            activity_date=activity['activity_date'],
            summary_polyline=activity['polyline'],
            parent_tour=tour[0].tour_uuid,
            user_id=current_user.uuid
        ))
    db.session.commit()
    return redirect(url_for('main.tour_detail', uuid=tour[0].tour_uuid))


@bp.route('/deletetour/<uuid>', methods=['GET'])
@jwt_required()
def delete_tour(uuid):
    tour = db.session.execute(db.select(Tour).filter_by(tour_uuid=uuid)).first()

    if tour[0].user.uuid == current_user.uuid:
        db.session.delete(tour[0])
        db.session.commit()
        return redirect(url_for('main.user_profile'))
    else:
        print('naughty')
        return redirect(url_for('main.index'))
    # TODO make sure user can only delete their own tours

tourtracker_app/main/templates/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Tour Tracker</title>
    <!-- <script type="module" src="/static/built/maps.js"></script> -->
    <script type="module" src="/static/built/drawmap.js"></script>
    <link href="/static/common.css" rel="stylesheet">
    {% block head %}{% endblock %}
  </head>
  <body>
    <div class="container" id="container">
        {% block content %}{% endblock %}
    </div>
  </body>
</html>

tourtracker_app/main/templates/create_tour.html
{% extends "base.html" %}
{% block content %}
        <div class="navbar" id="navbar">
        <ul class="navbar__content noBullets">
            <li>
                <a href={{ url_for('main.index') }}><img src="/static/assets/images/tourtracker_logo.png"
                     height="50px"
                   alt="The tourtracker website logo"></a>
            </li>
        </ul>
    </div>
  {% if strava_authenticated %}
    <form method="POST" action="/createtour" class="form">
      {{ form.csrf_token }}
        <p>{{ form.tour_name.label }}</p>
      {{ form.tour_name(class="form__input") }}
        <p>{{ form.start_date.label }}</p>
      {{ form.start_date(class="form__input")  }}
{#      {{ form.auto_refresh(class="form__input")  }}#}
        <p>{{ form.end_date.label }}</p>
      {{ form.end_date(class="form__input")  }}
      {{ form.submit(class="button pointer") }}
    </form>
  {% endif %}
{% endblock %}

tourtracker_app/main/templates/index.html
{% extends "base.html" %}
{%  block head %}
    <script type="module" src="/static/built/index.js"></script>
{% endblock %}


{% block content %}
    <div class="navbar" id="navbar">
        <ul class="navbar__content noBullets">
            <li>
                <img src="static/assets/images/tourtracker_logo.png"
                     height="50px"
                     alt="The tourtracker website logo">
                <img src="/static/assets/images/api_logo_pwrdBy_strava_stack_light.png"
                     height="50px"
                     alt="Powered by Strava">
            </li>

            <li id="hamburgerToggle">
                <img src="static/assets/images/icons8-hamburger-menu-48.png"
                     height=40px
                     width=40px
                     alt="The hamburger menu icon"
                     id="openIcon"
                     class="pointer">
                <img src="static/assets/images/icons8-multiply-48.png"
                     height="40px"
                     width="40px"
                     alt="The close menu icon"
                     id="closeIcon"
                     class="pointer">
            </li>
        </ul>
    </div>

    <div class="homeContent">
        <div class="hamburgerMenu">
            <ul class="hamburgerMenu__items noBullets">
                <li class="pointer"><p>Features</p></li>
                <li class="pointer"><p>About TourTracker</p></li>
                <li class="pointer"><p>Help</p></li>
            </ul>
        </div>
        <div class="home-splash home-splash-img" id="home-splash">
            <h1>This is TourTracker</h1>
            <h3>Making it easy to track, record and share your bike tours.</h3>
          <form class="form">
            <button class="button pointer" type="submit" formaction={{ url_for('auth.login') }}>Log In</button>
            <button class="button pointer" type="submit" formaction={{ url_for('auth.signup') }}>Sign Up</button>
          </form>
    </div>
        <div class="home-outline">
            <div class="home-outline__text">
                <h3>Connect your Strava account</h3>
                <p>Let Strava know that you're happy to share some of your data with TourTracker</p>
            </div>
            <div class="home-outline__image">
                <!-- TODO these don't seem to be working -->
                <img
                    srcset="/static/assets/images/DSC_0168_1600.jpg 1600w,
                            /static/assets/images/DSC_0168_800.jpg 800w,
                            /static/assets/images/DSC_0168_480.jpg 480w"
                    sizes="(max-width: 1000px) 100vw, (min-width: 1001px) 50vw"
                    src="/static/assets/images/DSC_0168_1600.jpg"
                    alt="A cyclist on a salt pan">
            </div>
            <div class="home-outline__text">
                <h3>Go ride and enjoy your tour</h3>
                <p>Upload your rides to Strava as you normally would</p>
            </div>
            <div class="home-outline__image">
                <img
                    srcset="/static/assets/images/DSC_0665_1600.jpg 1600w,
                            /static/assets/images/DSC_0665_800.jpg 800w,
                            /static/assets/images/DSC_0665_480.jpg 480w"
                    sizes="(max-width: 1000px) 100vw, (min-width: 1001px) 50vw"
                    src="/static/assets/images/DSC_0665_1600.jpg"
                    alt="A view towards Monte Fitzroy">
            </div>
            <div class="home-outline__text">
                <h3>TourTracker automatically updates</h3>
                <p>TourTracker will handle everything in the background and your tour stats and map will update shortly after you upload your Strava activity</p>
            </div>
            <div class="home-outline__image">
                <img
                    srcset="/static/assets/images/DSC_0000_1600.jpg 1600w,
                            /static/assets/images/DSC_0000_800.jpg 800w,
                            /static/assets/images/DSC_0000_480.jpg 480w"
                    sizes="(max-width: 1000px) 100vw, (min-width: 1001px) 50vw"
                    src="/static/assets/images/DSC_0000_1600.jpg"
                    alt="A winding road in Mexico">
            </div>
            <div class="home-outline__text">
                <h3>Share your tour!</h3>
                <p>Share your live tour stats either by sending a link to friends and family or embedding TourTracker in your own website.</p>
                <form>
                    <button class="button pointer" type="submit" formaction={{ url_for('auth.signup') }}>Sign Up</button>
                </form>

            </div>
            <div class="home-outline__image">
                <img
                    srcset="/static/assets/images/DSC03334_1600.jpg 1600w,
                            /static/assets/images/DSC03334_800.jpg 800w,
                            /static/assets/images/DSC03334_480.jpg 480w"
                    sizes="(max-width: 1000px) 100vw, (min-width: 1001px) 50vw"
                    src="/static/assets/images/DSC03334_1600.jpg"
                    alt="A cyclist and his bike">
            </div>

        </div>
    </div>


    <div class="footer">
        <p class="acknowledgments">Site by <a href="https://tw-smith.me" target="_blank">Toby Smith</a>.
            Icons by <a href="https://icons8.com/" target="_blank">icons8</a></p>
    </div>







{% endblock %}
    

tourtracker_app/main/templates/tourdetail.html
{% extends "base.html" %}
{% block content %}
    <div class="navbar" id="navbar">
    <ul class="navbar__content noBullets">
        <li>
            <a href={{ url_for('main.index') }}><img src="/static/assets/images/tourtracker_logo.png"
                 height="50px"
               alt="The tourtracker website logo"></a>
        </li>
    </ul>
</div>
<h1>Tour Detail</h1>
<h3>{{ tour.tour_name }}</h3>

<div id="map"></div>
<script async
src="https://maps.googleapis.com/maps/api/js?key={{config['GOOGLE_MAPS_API_KEY']}}&callback=initMap&v=weekly"
defer
></script>

<form class="form">
    <button type="submit" class="button pointer" formaction={{ url_for('main.refresh_tour', uuid=tour.tour_uuid) }}>Refresh</button>
    <button type="submit" class="button pointer" formaction={{ url_for('main.user_profile') }}>User Profile</button>
    <button type="submit" class="button pointer" formaction={{ url_for('main.delete_tour', uuid=tour.tour_uuid) }}>Delete Tour</button>
</form>

{% endblock %}

tourtracker_app/main/templates/tourembed.html
{% extends "base.html" %}
{% block content %}

<div id="map"></div>
<script async
src="https://maps.googleapis.com/maps/api/js?key={{config['GOOGLE_MAPS_API_KEY']}}&callback=initMap&v=weekly"
defer
></script>


{% endblock %}

tourtracker_app/main/templates/user_profile.html
{% extends "base.html" %}
{% block content %}
    <div class="navbar" id="navbar">
        <ul class="navbar__content noBullets">
            <li>
                <a href={{ url_for('main.index') }}><img src="/static/assets/images/tourtracker_logo.png"
                     height="50px"
                   alt="The tourtracker website logo"></a>
            </li>
        </ul>
    </div>
  <h1 id="draw">Tour Tracker</h1>

  {% with messages = get_flashed_messages() %}
  {% if messages %}
  {% for message in messages %}
      <h3 class="form__error">{{ message }}</h3>
  {% endfor %}
  {% endif %}
  {% endwith %}

  <p>Username: {{ username }}</p>

{#  {% if strava_authenticated %}#}
{#    <form method="POST" action="/createtour" class="form">#}
{#      {{ form.csrf_token }}#}
{#        <p>{{ form.tour_name.label }}</p>#}
{#      {{ form.tour_name(class="form__input") }}#}
{#        <p>{{ form.start_date.label }}</p>#}
{#      {{ form.start_date(class="form__input")  }}#}
{#      {{ form.auto_refresh(class="form__input")  }}#}
{#        <p>{{ form.end_date.label }}</p>#}
{#      {{ form.end_date(class="form__input")  }}#}
{#      {{ form.submit(class="button pointer") }}#}
{#    </form>#}
{#  {% endif %}#}

    {% if user_tours %}
        <div class="tour-table">
            <p class="tour-table__name">Tour Name</p>
            <p class="tour-table__start-date">Start Date</p>
            <p class="tour-table__end-date">End Date</p>
            {% for tour in user_tours %}
                <a class="tour-table__name" href={{ url_for('main.tour_detail', uuid=tour.tour_uuid) }}>{{ tour.tour_name }}</a>
                <p class="tour-table__start-date">{{ tour.start_date | timestamp_to_str }}</p>
                <p class="tour-table__end-date">{{ tour.end_date | timestamp_to_str }}</p>
            {% endfor %}
        </div>

    {% endif %}

{#    <form class="form">#}
{#      <button class="button pointer" type="submit" formaction={{ url_for('auth.logout') }}>Log Out</button>#}
{#    </form>#}


{#  {% else %}#}
{#    <form class="form">#}
{#      <button class="button pointer" type="submit" formaction={{ url_for('strava_api_auth.strava_auth') }}>Link Strava</button>#}
{#      <button class="button pointer" type="submit" formaction={{ url_for('auth.logout') }}>Log Out</button>#}
{#   </form>#}
{#  {% endif %}#}

        <form>
      {% if not strava_authenticated %}

            <button class="button pointer" type="submit" formaction={{ url_for('strava_api_auth.strava_auth') }}>Link Strava</button>
      {% else %}
              <button class="button pointer" type="submit" formaction={{ url_for('main.create_tour') }}>Create Tour</button>
              <button class="button pointer" type="submit" formaction={{ url_for('strava_api_auth.strava_deauth') }}>Unlink Strava</button>
      {% endif %}
      {% if is_admin %}
        <button class="button pointer" type="submit" formaction={{ url_for('strava_webhook.webhook_admin') }}>Webhook Admin</button>
      {% endif %}
      <button class="button pointer" type="submit" formaction={{ url_for('auth.logout') }}>Log Out</button>
    </form>

   
  {% endblock %}


 







    